flowchart TB
    n1_Whereistheresource["Where is the resource?"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_Whereistheresource fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_Region["Region"]
    style n2_Region fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_AZ["AZ"]
    style n3_AZ fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_Region --> n3_AZ
