flowchart TB
    n1_AvailabilityZonesAZs["Availability Zones (AZs)"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_AvailabilityZonesAZs fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_CanadaCentral["Canada Central"]
    style n2_CanadaCentral fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_AZ1["AZ-1"]
    style n3_AZ1 fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n4_AZ2["AZ-2"]
    style n4_AZ2 fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n5_AZ3["AZ-3"]
    style n5_AZ3 fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_CanadaCentral --> n3_AZ1
    n3_AZ1 --> n4_AZ2
    n4_AZ2 --> n5_AZ3
