flowchart TB
    n1_SecurityHubSeverityMappi["Security Hub Severity Mapping"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_SecurityHubSeverityMappi fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_Critical["Critical"]
    style n2_Critical fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_High["High"]
    style n3_High fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n4_Medium["Medium"]
    style n4_Medium fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_Critical --> n3_High
    n3_High --> n4_Medium
