flowchart TB
    n1_ExampleDangerousConfigur["Example: Dangerous Configuration"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_ExampleDangerousConfigur fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_Internet["Internet"]
    style n2_Internet fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_Port22Open["Port 22 Open"]
    style n3_Port22Open fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n4_EC2Instance["EC2 Instance"]
    style n4_EC2Instance fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_Internet --> n3_Port22Open
    n3_Port22Open --> n4_EC2Instance
