flowchart TB
    n1_LogtoS3["Log to S3"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_LogtoS3 fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_CloudTrail["CloudTrail"]
    style n2_CloudTrail fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_S3Storage["S3 Storage"]
    style n3_S3Storage fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_CloudTrail --> n3_S3Storage
