flowchart TB
    n1_HowThisRelatestoSOCOpera["How This Relates to SOC Operations"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_HowThisRelatestoSOCOpera fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_ReadUser["Read User"]
    style n2_ReadUser fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_AdminUser["Admin User"]
    style n3_AdminUser fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_ReadUser --> n3_AdminUser
