flowchart TB
    n1_Risk["Risk"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_Risk fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_CompromisedUser["Compromised User"]
    style n2_CompromisedUser fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_AdministratorAccess["AdministratorAccess"]
    style n3_AdministratorAccess fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n4_FullAWSEnvironmentContro["Full AWS Environment Control"]
    style n4_FullAWSEnvironmentContro fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_CompromisedUser --> n3_AdministratorAccess
    n3_AdministratorAccess --> n4_FullAWSEnvironmentContro
