flowchart TB
    n1_AWSCloudNative["AWS Cloud-Native"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_AWSCloudNative fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_AWSConfig["AWS Config"]
    style n2_AWSConfig fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_CloudWatch["CloudWatch"]
    style n3_CloudWatch fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_AWSConfig --> n3_CloudWatch
