flowchart TB
    n1_WhataMetricFilterDoes["What a Metric Filter Does"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_WhataMetricFilterDoes fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_LogEntryMatchesPattern["Log Entry Matches Pattern"]
    style n2_LogEntryMatchesPattern fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_Metric1["Metric +1"]
    style n3_Metric1 fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_LogEntryMatchesPattern --> n3_Metric1
