flowchart TB
    n1_LambdaFunction["Lambda Function"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_LambdaFunction fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_FailedSSHAttack["Failed SSH Attack"]
    style n2_FailedSSHAttack fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_Lambda["Lambda"]
    style n3_Lambda fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n4_UpdateFirewall["Update Firewall"]
    style n4_UpdateFirewall fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_FailedSSHAttack --> n3_Lambda
    n3_Lambda --> n4_UpdateFirewall
