flowchart TB
    n1_EmailNotification["Email Notification"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_EmailNotification fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_Alarm["Alarm"]
    style n2_Alarm fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_SNS["SNS"]
    style n3_SNS fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n4_SOCAnalyst["SOC Analyst"]
    style n4_SOCAnalyst fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_Alarm --> n3_SNS
    n3_SNS --> n4_SOCAnalyst
