flowchart TB
    n1_Diagram123["Diagram 123"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_Diagram123 fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_Humanreadabletext["Human-readable text"]
    style n2_Humanreadabletext fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_Machinereadablenumber["Machine-readable number"]
    style n3_Machinereadablenumber fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_Humanreadabletext --> n3_Machinereadablenumber
