flowchart TB
    n1_Architecture["Architecture"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_Architecture fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_EC2Instance["EC2 Instance"]
    style n2_EC2Instance fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_InstanceProfileRole["Instance Profile Role"]
    style n3_InstanceProfileRole fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n4_CloudWatchAgent["CloudWatch Agent"]
    style n4_CloudWatchAgent fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n5_CloudWatchLogs["CloudWatch Logs"]
    style n5_CloudWatchLogs fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_EC2Instance --> n3_InstanceProfileRole
    n3_InstanceProfileRole --> n4_CloudWatchAgent
    n4_CloudWatchAgent --> n5_CloudWatchLogs
