flowchart TB
    n1_GroupSimilarEvents["Group Similar Events"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_GroupSimilarEvents fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_1000failedlogins["1000 failed logins"]
    style n2_1000failedlogins fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_Singleauthenticationpatt["Single authentication pattern"]
    style n3_Singleauthenticationpatt fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_1000failedlogins --> n3_Singleauthenticationpatt
