flowchart TB
    n1_TypicalFlow["Typical Flow"]
    classDef titleNode fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    style n1_TypicalFlow fill:#EFF6FF,stroke:#2563EB,stroke-width:2px,color:#0F172A
    n2_EC2Instance["EC2 Instance"]
    style n2_EC2Instance fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n3_CloudWatchAgent["CloudWatch Agent"]
    style n3_CloudWatchAgent fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n4_CloudWatchLogs["CloudWatch Logs"]
    style n4_CloudWatchLogs fill:#FFFFFF,stroke:#93C5FD,stroke-width:2px,color:#0F172A
    n2_EC2Instance --> n3_CloudWatchAgent
    n3_CloudWatchAgent --> n4_CloudWatchLogs
