"""Cybersecurity / AWS acronym expansions for presenter notes."""
from __future__ import annotations

import re

ABBREVIATIONS: dict[str, str] = {
    "ATT&CK": "Adversarial Tactics, Techniques, and Common Knowledge",
    "MITRE": "MITRE Corporation",
    "SIEM": "Security Information and Event Management",
    "SOAR": "Security Orchestration, Automation, and Response",
    "CSPM": "Cloud Security Posture Management",
    "CNAPP": "Cloud-Native Application Protection Platform",
    "CWPP": "Cloud Workload Protection Platform",
    "EDR": "Endpoint Detection and Response",
    "XDR": "Extended Detection and Response",
    "MDR": "Managed Detection and Response",
    "UEBA": "User and Entity Behavior Analytics",
    "DFIR": "Digital Forensics and Incident Response",
    "IAM": "Identity and Access Management",
    "MFA": "Multi-Factor Authentication",
    "2FA": "Two-Factor Authentication",
    "ACL": "Access Control List",
    "NACL": "Network Access Control List",
    "RBAC": "Role-Based Access Control",
    "ABAC": "Attribute-Based Access Control",
    "VPC": "Virtual Private Cloud",
    "EC2": "Elastic Compute Cloud",
    "EBS": "Elastic Block Store",
    "EFS": "Elastic File System",
    "S3": "Simple Storage Service",
    "RDS": "Relational Database Service",
    "ECS": "Elastic Container Service",
    "EKS": "Elastic Kubernetes Service",
    "EMF": "Embedded Metric Format",
    "API": "Application Programming Interface",
    "CLI": "Command Line Interface",
    "SSH": "Secure Shell",
    "HTTPS": "Hypertext Transfer Protocol Secure",
    "HTTP": "Hypertext Transfer Protocol",
    "TLS": "Transport Layer Security",
    "SSL": "Secure Sockets Layer",
    "DNS": "Domain Name System",
    "DDoS": "Distributed Denial of Service",
    "DoS": "Denial of Service",
    "NAT": "Network Address Translation",
    "IGW": "Internet Gateway",
    "CIDR": "Classless Inter-Domain Routing",
    "JSON": "JavaScript Object Notation",
    "JWT": "JSON Web Token",
    "OIDC": "OpenID Connect",
    "SAML": "Security Assertion Markup Language",
    "SSO": "Single Sign-On",
    "LDAP": "Lightweight Directory Access Protocol",
    "KMS": "Key Management Service",
    "HSM": "Hardware Security Module",
    "SSE": "Server-Side Encryption",
    "ARN": "Amazon Resource Name",
    "AMI": "Amazon Machine Image",
    "SOC": "Security Operations Center",
    "AWS": "Amazon Web Services",
    "AZs": "Availability Zones",
    "AZ": "Availability Zone",
    "CPU": "Central Processing Unit",
    "OS": "Operating System",
    "VMs": "Virtual Machines",
    "VM": "Virtual Machine",
    "AI": "Artificial Intelligence",
    "ML": "Machine Learning",
    "LLM": "Large Language Model",
    "GenAI": "Generative Artificial Intelligence",
    "NLP": "Natural Language Processing",
    "RAG": "Retrieval-Augmented Generation",
    "KPIs": "Key Performance Indicators",
    "KPI": "Key Performance Indicator",
    "ROI": "Return on Investment",
    "SLA": "Service Level Agreement",
    "SLO": "Service Level Objective",
    "SLI": "Service Level Indicator",
    "MTTR": "Mean Time to Respond",
    "MTTD": "Mean Time to Detect",
    "RTO": "Recovery Time Objective",
    "RPO": "Recovery Point Objective",
    "BCP": "Business Continuity Plan",
    "DR": "Disaster Recovery",
    "HA": "High Availability",
    "IaC": "Infrastructure as Code",
    "IDS": "Intrusion Detection System",
    "IPS": "Intrusion Prevention System",
    "WAF": "Web Application Firewall",
    "DLP": "Data Loss Prevention",
    "PII": "Personally Identifiable Information",
    "PHI": "Protected Health Information",
    "GDPR": "General Data Protection Regulation",
    "HIPAA": "Health Insurance Portability and Accountability Act",
    "PCI": "Payment Card Industry",
    "NIST": "National Institute of Standards and Technology",
    "CVE": "Common Vulnerabilities and Exposures",
    "CVSS": "Common Vulnerability Scoring System",
    "IOC": "Indicator of Compromise",
    "IOA": "Indicator of Attack",
    "TTPs": "Tactics, Techniques, and Procedures",
    "TTP": "Tactics, Techniques, and Procedures",
    "APT": "Advanced Persistent Threat",
    "CTI": "Cyber Threat Intelligence",
    "OSINT": "Open Source Intelligence",
    "IR": "Incident Response",
    "CSIRT": "Computer Security Incident Response Team",
    "CERT": "Computer Emergency Response Team",
    "SAST": "Static Application Security Testing",
    "DAST": "Dynamic Application Security Testing",
    "IAST": "Interactive Application Security Testing",
    "SCA": "Software Composition Analysis",
    "SBOM": "Software Bill of Materials",
    "SetUID": "Set User ID",
    "SUID": "Set User ID",
    "UID": "User Identifier",
    "GID": "Group Identifier",
    "OTP": "One-Time Password",
    "TOTP": "Time-based One-Time Password",
    "PKI": "Public Key Infrastructure",
    "SaaS": "Software as a Service",
    "PaaS": "Platform as a Service",
    "IaaS": "Infrastructure as a Service",
    "VPN": "Virtual Private Network",
    "CDN": "Content Delivery Network",
    "ELB": "Elastic Load Balancing",
    "ALB": "Application Load Balancer",
    "NLB": "Network Load Balancer",
    "SNS": "Simple Notification Service",
    "SQS": "Simple Queue Service",
    "STS": "Security Token Service",
    "CORS": "Cross-Origin Resource Sharing",
    "SQL": "Structured Query Language",
    "NoSQL": "Not Only SQL",
    "XML": "Extensible Markup Language",
    "IPv4": "Internet Protocol version 4",
    "IPv6": "Internet Protocol version 6",
    "TCP": "Transmission Control Protocol",
    "UDP": "User Datagram Protocol",
    "ICMP": "Internet Control Message Protocol",
    "FTP": "File Transfer Protocol",
    "SFTP": "SSH File Transfer Protocol",
    "SCP": "Secure Copy Protocol",
    "RDP": "Remote Desktop Protocol",
    "SMB": "Server Message Block",
    "NGINX": "NGINX web server",
    "sudo": "superuser do",
    "chmod": "change mode",
    "chown": "change owner",
    "auditd": "Linux audit daemon",
    "journald": "systemd journal daemon",
    "DevSecOps": "Development, Security, and Operations",
    "DevOps": "Development and Operations",
    "GitOps": "Git-based Operations",
    "KQL": "Kusto Query Language",
    "PCAP": "Packet Capture",
    "URL": "Uniform Resource Locator",
    "URI": "Uniform Resource Identifier",
    "HTML": "Hypertext Markup Language",
    "IDE": "Integrated Development Environment",
    "SDK": "Software Development Kit",
    "GUI": "Graphical User Interface",
    "IoT": "Internet of Things",
    "OT": "Operational Technology",
    "IT": "Information Technology",
    "PoC": "Proof of Concept",
    "MVP": "Minimum Viable Product",
    "CRUD": "Create, Read, Update, Delete",
    "REST": "Representational State Transfer",
    "OAuth": "Open Authorization",
    "BYOD": "Bring Your Own Device",
    "MDM": "Mobile Device Management",
    "CASB": "Cloud Access Security Broker",
    "ZTNA": "Zero Trust Network Access",
    "ZTA": "Zero Trust Architecture",
    "NGFW": "Next-Generation Firewall",
    "HIDS": "Host-based Intrusion Detection System",
    "NIDS": "Network-based Intrusion Detection System",
    "EPP": "Endpoint Protection Platform",
    "PAM": "Privileged Access Management",
    "IGA": "Identity Governance and Administration",
    "GRC": "Governance, Risk, and Compliance",
    "CIA": "Confidentiality, Integrity, and Availability",
    "CISO": "Chief Information Security Officer",
    "MSSP": "Managed Security Service Provider",
    "MSP": "Managed Service Provider",
    "CloudTrail": "AWS CloudTrail audit logging",
    "GuardDuty": "Amazon GuardDuty threat detection",
    "CloudWatch": "Amazon CloudWatch monitoring",
    "Inspector": "Amazon Inspector vulnerability assessment",
    "CloudFormation": "AWS CloudFormation infrastructure as code",
    "Lambda": "AWS Lambda serverless compute",
    "CloudFront": "Amazon CloudFront content delivery",
    "DynamoDB": "Amazon DynamoDB NoSQL database",
    "Aurora": "Amazon Aurora relational database",
    "Redshift": "Amazon Redshift data warehouse",
    "Athena": "Amazon Athena query service",
    "Glue": "AWS Glue data integration",
    "Kinesis": "Amazon Kinesis data streaming",
    "OpenSearch": "Amazon OpenSearch search and analytics",
    "Bedrock": "Amazon Bedrock generative AI",
    "SageMaker": "Amazon SageMaker machine learning",
    "CSV": "Comma-Separated Values",
    "BPA": "Block Public Access",
    "PIN": "Personal Identification Number",
    "FHS": "Filesystem Hierarchy Standard",
    "IP": "Internet Protocol",
    "Security Hub": "AWS Security Hub",
    "Route53": "Amazon Route 53 DNS service",
    "Access Analyzer": "IAM Access Analyzer",
    "CloudWatch Agent": "Amazon CloudWatch Agent",
    "Logs Insights": "CloudWatch Logs Insights",
    "sshd": "SSH daemon (Secure Shell daemon)",
    "nginx": "NGINX web server",
    "SOCs": "Security Operations Centers",
    "APIs": "Application Programming Interfaces",
    "VPCs": "Virtual Private Clouds",
    "EC2s": "Elastic Compute Cloud instances",
}

SKIP_ALWAYS = frozenset({"OR", "IF", "IN", "ON", "TO", "BY", "AT", "AS", "IS", "AN", "BE"})

_SORTED_ABBR = sorted(
    ((k, v) for k, v in ABBREVIATIONS.items() if k not in SKIP_ALWAYS),
    key=lambda kv: len(kv[0]),
    reverse=True,
)


def _full_form_present(text: str, full: str) -> bool:
    return bool(re.search(rf"\b{re.escape(full)}\b", text, re.IGNORECASE))


def _already_expanded(text: str, abbr: str, full: str) -> bool:
    if re.search(rf"\b{re.escape(abbr)}\s*\({re.escape(full)}\)", text):
        return True
    if _full_form_present(text, full):
        return True
    return False


def expand_abbreviations(text: str) -> str:
    """Expand abbreviations for presenter notes: EC2 -> EC2 (Elastic Compute Cloud)."""
    if not text:
        return text
    for abbr, full in _SORTED_ABBR:
        if _full_form_present(text, full):
            text = re.sub(rf"\s*\({re.escape(abbr)}\)", "", text)
        else:
            text = re.sub(rf"\({re.escape(abbr)}\)", f"({full})", text)
    for abbr, full in _SORTED_ABBR:
        if _already_expanded(text, abbr, full):
            continue
        pattern = rf"(?<![(\w/])\b({re.escape(abbr)})\b(?!\s*\()"
        text = re.sub(pattern, rf"\1 ({full})", text)
    return text
